repos:
  - repo: local
    hooks:
      - id: total-analyzer
        name: TOTAL Analyzer
        description: Scans Python files for SQL injections and crypto offload opportunities
        entry: bash -c 'total-analyzer "$@" --sarif > .total-report.sarif && cat .total-report.sarif | jq -e ".runs[0].results | any(.level == \"error\")" && exit 1 || exit 0' --
        language: system
        files: \.py$
        require_serial: true
        pass_filenames: true
        verbose: true
